from typing import Protocol, ContextManager
from grokbuddy.domain.model import DeliveryReceipt, NormalizedEvent


class Repository(Protocol):
    def get(self, table: str, identity: str) -> dict: ...
    def find(self, table: str, **filters) -> list[dict]: ...
    def add(self, table: str, record: dict) -> None: ...
    def save(self, table: str, record: dict, expected_version: int | None = None) -> None: ...


class Database(Protocol):
    def transaction(self) -> ContextManager[Repository]: ...


class Clock(Protocol):
    def now(self) -> int: ...  # UTC microseconds


class ArtifactStore(Protocol):
    def put(self, content: bytes) -> tuple[str, str]: ...
    def read(self, pointer: str, expected_hash: str, size: int) -> bytes: ...


class ContractValidator(Protocol):
    def validate(self, kind: str, value: dict) -> None: ...


class ReviewerAdapter(Protocol):
    def submit_review_request(self, envelope: dict, delivery_key: str) -> DeliveryReceipt: ...
    def get_delivery_status(self, delivery_key: str) -> DeliveryReceipt: ...
    def normalize_review_event(self, raw: dict, verified_actor_id: str) -> NormalizedEvent: ...


class GitHubCommentTransport(Protocol):
    """Ordinary PR-comment projection only; never merge, approve, or push."""
    def find_comment(self, binding: dict, marker: str) -> dict | None: ...
    def create_comment(self, binding: dict, body: str) -> dict: ...
    def update_comment(self, binding: dict, comment_id: str, body: str) -> dict: ...


class ReviewQueue(Protocol):
    """The Mock receives only this queue port, never a Task repository or Hub."""
    def enqueue(self, key: str, envelope: dict) -> None: ...
    def contains(self, key: str) -> bool: ...
    def take(self) -> dict | None: ...
    def complete(self, job: dict, events: list[NormalizedEvent]) -> None: ...
